### ISSUE TITLE
using `PowerDynamics: Perturbation` fails

### ISSUE THREAD

**Issue by LRydin** [JuliaEnergy/PowerDynamics.jl#200]
Hey all,

a simple call like:

```julia
using PowerDynamics: Perturbation
```

fails. This came about following the [ieee14-minimal](https://github.com/JuliaEnergy/PowerDynamicsExamples/blob/master/ieee14-minimal/runexample.ipynb) example.

julia `v1.8.1`, linux kernel `5.19`.

It returns:

```
UndefVarError: Perturbation not defined

Stacktrace:
 [1] eval
   @ ./boot.jl:368 [inlined]
 [2] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1428
```

---

NB:

```julia
using PowerDynamics: LineFault
```
also fails.

**Comment by antonplietzsch** [comment]
Hey Leonardo,

this is not a `PowerDynamics` bug. The problem is rather that the `PowerDynamicsExamples` repository has not been updated for quite some while and there have been breaking changes in `PowerDynamics` in the meanwhile.

For a working example please have a look at the scripts in the [IEEE14 examples folder](https://github.com/JuliaEnergy/PowerDynamics.jl/tree/main/examples/ieee14bus) in the `PowerDynamics` repository which are always up to date with the newest release. Unfortunately, there is no online jupyter notebook for that (yet), so you have to either download the files or clone the whole repository for running the scripts.

However, thanks for the hint. We should either put some work into updating the `PowerDynamicsExamples` repository or archive it to avoid confusion in the future.

**Comment by LRydin** [comment]
Ah, alright, good to know. I'll use the examples in `PowerDynamics` then. Cheers!
