### ISSUE TITLE
Can't install PowerDynamics.jl due to SciMLBase compat

### ISSUE THREAD

**Issue by white-alistair** [JuliaEnergy/PowerDynamics.jl#214]
https://github.com/JuliaEnergy/PowerDynamics.jl/blob/2f8397088a1eeb7826ddda93ad90916ab8ccf056/Project.toml#L54

Hi, is there a reason to have an upper limit on the minor version of SciMLBase? This seems unnecessary as long as SciMLBase obeys semver, which it should. As a result I can't install PowerDynamics.jl due to unsatisfiable requirements with other packages in my project.

**Comment by white-alistair** [comment]
@AnnaBuettner I was planning to revisit the power grids experiment today but I'm blocked by this. I'll work on other things in the meantime but would you mind taking a look when you get a chance?

**Comment by hexaeder** [comment]
Unfortunately the upper bound is necessary, yes. SciML changed significantly how symbols of states are handled internally, something NetworkDynamics and PowerDynamics relied on since we construct our own `ODEFunction` objects (ref https://github.com/PIK-ICoNe/NetworkDynamics.jl/issues/132).
Do you need it in the same project necessarily or can you create the data with PD.jl in a different environment with `SciMLBase@2.10`?

**Comment by white-alistair** [comment]
Ahh I see. Sorry I didn't check the existing issues to see if this had already been discussed. I'll close this issue now.
