### ISSUE TITLE
`import` statements over `using`

### ISSUE THREAD

**Issue by timkittel** [JuliaEnergy/PowerDynamics.jl#25]
Hi @FHell, @SabineAuer, @luap-pik, @antonplietzsch,

Lucas, (@lima-lima), mentioned [here](https://github.com/JuliaEnergy/PowerDynamics.jl/issues/15#issuecomment-470856228), that it is actually a good idea to use only `import` statements instead of `using` inside of PowerDynamics packages to keep the namespace clean.

Do you have any opinions on that?

I personally think, that it would be a really good idea for the following reasons:

* clean namespace, you always know whats loaded
* stability againsnt future changes: If other packages start to export objects with the same name that we use, PowerDynamics may break with `using`
* @WouterVer had some problems when getting into PowerDynamics as to know where what comes from. This should be easier when using `import`.

Cheers,
Tim

PS: It's a bit embarrassing that I didn't think of that myself (:

**Comment by luap-pik** [comment]
I totally support this. :+1:

**Comment by FHell** [comment]
I am a big fan of using import only, possibly with shortcuts:

```import DifferentialEquations
const DE = DifferentialEquations
```

It's not very Juliaesque I guess. But as per the Python Koan: "Explicit is better than implicit."

Is there anything to consider with multiple dispatch that might not work?

**Comment by timkittel** [comment]
> possibly with shortcuts:
> 
> ```
> import DifferentialEquations
> const DE = DifferentialEquations
> ```

Yeah, I don't really like it, but I guess you are right and it would be useful and make the code more readable (:

> Is there anything to consider with multiple dispatch that might not work?

As far as I know, no. If you add a method to a function from an external package, you have to `import` it anyway.

**Comment by Lima-Lima** [comment]
Regarding multiple dispatch issues with the aliasing import scheme: 
> As far as I know, no. If you add a method to a function from an external package, you have to import it anyway.

This is correct. In order to extend the methods of a function it has to be hard linked in by using `import`. Further, the `const alias` won't interfere with the dispatch mechanism. I think it will resolve back at the untyped (first level) Julia IR. 

Regarding this topic in general (`import` vs `using`): I hadn't thought much about this prior to posting my code concept; and I had used `import` habitually based on years of Python. It made sense to limit the namespace like @FHell suggested: 

> `import DifferentialEquations`
`const DE = DifferentialEquations`

analogous to Python's `import LongModuleName as LMN`.

I agree with Tim here that the approach is rife with discomfort. Not using the short alias makes the code difficult to read and type; using the short alias reintroduces the ambiguity that we attempted to resolve by `import` in the first place: It's no longer explicit from where the functions come. 

I'm reconsidering the use of `import` by default in favor of `using` by default. Because of Julia's multiple dispatch, and if our package and those with which it interacts are well behaved ([avoiding type piracy](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Avoid-type-piracy-1)), then there is very low risk of a namespace collision. For a collision to happen the function name and the type of each argument would have to collide, when defining dispatch including types of our own creation this won't happen. Any methods that are created in PowerDynamics which might collide with other packages shouldn't be exported.

Further, `using` ensures that we don't extend the methods of the external modules. As aforementioned, it's only possible to extend the methods when using `import`. 

These factors suggest `using` is both easier for the developer and more polite to the ecosystem. My intuition yesterday was off the mark for Julia, I think. 

In the absence of any clear guidance on this in the Julia documentation, I took a look at some of the most popular large packages. Anecdotally:

**DifferentialEquations** seems to use `using` unless the method will be extended, in which case `import`. 
**JuMP** is the same, but has more `import` statements and [sometimes](https://github.com/JuliaOpt/JuMP.jl/blob/c01802926c34aa30e5d272ac1063f1595084aa4a/src/JuMP.jl#L16) mirrors the style we're discussing:

 ```
import MathOptInterface 
const MOI = MathOptInterface
```
Notably, both packages only `import` or `using` at the top level of the module. XYZ module only has `import/using` statements in XYZ.jl, none of the component files which are `include()`ed have any additional package imports. 

**Knet** is the same regarding `using` / `import`: it seems to default to `using` unless the methods need extending, in which case `import` is used. However, Knet does have modules added at the file level, not only in the "top level" XYZ.jl file. A different style choice. I prefer the top level having all the module `import/usings`, but not strongly. 

My suggestion would be:
1. Use `using` unless you are extending the methods. 
2. Use `using: X, Y, Z` to limit the scope of namespace pollution whenever the list of imported identifiers is small (less than 6 or so?)
3. And put all the `import` and `using` commands in the top level file of the module. 


As an example of point 3: 
[GridDynamics.jl](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/39d21af3540fc04ce125b3248c030bd87c4ef91e/src/GridDynamics.jl#L4) imports `Base.iterators: flatten` via `using`, and [DynamicNodeMacro](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/39d21af3540fc04ce125b3248c030bd87c4ef91e/src/DynamicNodeMacro.jl#L6) imports all of `Base.iterators` with `using`. Perhaps these are better consolidated in the top-level [PowerDynBase.jl](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/master/src/PowerDynBase.jl) and removed from the sub-files. This shouldn't have a performance impact, only style and ease of use. 

I didn't intend to stir things up by using `import`! But it is (at least for me) a good discussion to have. I'm interested in any thoughts from the group.

Best,
-Lucas

**Comment by timkittel** [comment]
As I mentioned earlier, I am supporting the idea of `import` not only in order to avoid cluttering the namespace but also so one always knows where something comes from. And I think for a library like PowerDynamics, where changes will still be happening on a regular level and more people are contacting to use it by the day, it might be a good idea to enable people to quickly get into code details (if they want). This is in particular important, as @FHell is also trying to get interns, bachelor's and master's students to work on it.

To circumvent the problems mentioned above, another way would be:

1. Always use
```Julia
import FooBar 
const FB = FooBar
```
1. and then use **only** `FB.objectorfunction` (with the short version).

It solves the problems
1. with accidentally adding methods as `import FooBar: objectorfunction` is not allowed and to overwrite, you need to specify it as
```Julia
function FB.objectorfunction(bla::MyType)
    ...
end
```
That should make it hard to accidentally add a method but easy to do if intended.
1. people always know where a function comes from. It makes the code a lot more readable.
1. And put all the `import` commands in the top level file of the module. (If one can recognize by the prefix (e.g. `FB`) where a function comes from, I totally agree here.)

That should take care of the problems and be (in my opinion) more understandable to new people and still keep a clean and short code.

(It's basically @FHell ' s suggestion, just with a bit more reasoning.)

**Comment by SabineAuer** [comment]
I agree that import statements would make the code more readable since sometimes I also had trouble tracking down where packages come from .

**Comment by janlisse** [comment]
I prefer "using" over "import", but in an explicit, qualified manner.
The semantics of "import" are meant for adding functions to methods and should only be used when
doing so.
When "using" is used in a qualified manner, people always know where a function comes from.
I agree with the practice of having all using/import statements at the top of the file.
