### ISSUE TITLE
Design of faults.

### ISSUE THREAD

**Issue by FHell** [JuliaEnergy/PowerDynamics.jl#41]
This issue is to discuss the structure of the implementation of faults. I started looking into building a generic design using callbacks to swap between normal and fault dynamics. However, this is more tricky than maybe expected. Reinitializing the integrator after switching the functions somehow triggers the callback again.

I have pushed this experiment to this branch:
https://github.com/JuliaEnergy/PowerDynamics.jl/tree/AlternativeDesign-faults

A short discussion on this design is here:
https://discourse.julialang.org/t/changing-the-righthand-side-in-a-callback/27462/6

I don't know where to best go from here. I don't think the design with a switch is good for us. Maybe someone can get the reinit based code to work. Or we resurrect the composite solution that Tim built (and maybe try to upstream it?)

**Comment by janlisse** [comment]
At least @luap-pik solution in the PowerDrop branch works:
https://github.com/JuliaEnergy/PowerDynamics.jl/blob/PowerDrop/src/simulations/PowerDrop.jl
I re(added) it in the simulate3() function. The code looks not nice but is fully functional.
But i guess there must be a more clean way to express the same?

**Comment by luap-pik** [comment]
I did not find a better way yet, but I could ask in the diffeq forum.
To handle a composite solution is not necessarily nicer :-)

**Comment by FHell** [comment]
Actually Chris Rackauckas also suggested to use the integrator interface now:

https://discourse.julialang.org/t/changing-the-righthand-side-in-a-callback/27462/7

I just realized that in order for our solution handling functions to also work with fault simulations we need to keep the information on the fault around. I think this necessitates changes in the PowerGrid Solution object.

I might have a crack at getting this to work using iterators in a slightly cleaner way when I'm back from holidays.

Paul, why did you use two integrator objects there BTW? Would something like this (pseudocode) work instead?

```
init!(integrator, tspan1)
solve!(integrator)
integrator.f = fault_f
reinit!(integrator, tspan2, delete_sol=false)
solve!(integrator)
integrator.f = original_f
reinit!(integrator, tspan3, delete_sol=false)
solve!(integrator)
```

**Comment by janlisse** [comment]
At least for the PowerDrop feature DiscreteCallbacks could be an option. Something like this:
```
struct Fault
    rhs_normal
    rhs_fault
    tstop1
    tstop2
end

function (f::Fault)(du,u,p,t)
    if (!p.has_failure)
        f.rhs_normal(du,u,p,t)
    else
        f.rhs_fault(du,u,p,t)
    end
end

function simulate4(pd::PowerDrop, powergrid, x0, timespan)
    fault = Fault(rhs(powergrid), rhs(pd(powergrid)), tspan_fault[1], tspan_fault[2])
    problem = ODEProblem{true}(fault, x0.vec, timespan)
    tstop1 = [tspan_fault[1]]
    tstop2 = [tspan_fault[2]]
    cb1 = DiscreteCallback((u,t,integrator) -> t in tstop1), integrator -> integrator.p = true)
    cb2 = DiscreteCallback((u,t,integrator) -> t in tstop2), integrator -> integrator.p = false)
    sol = solve(prob, Rodas4(autodiff=false), callback = [cb1, cb2], tstops=[tspan_fault[1];tspan_fault[2]])
end
```

**Comment by FHell** [comment]
@janlisse rhs(powergrid) is not a vanilla function though, but an ODEFunction:

https://docs.juliadiffeq.org/latest/features/performance_overloads.html#ODEFunction-1

Eventually we will want to include Jacobian information here as well. All that should be automatic if it is constructed by NetworkDynamics, but would need to be reproduced here "by hand".

**Comment by luap-pik** [comment]
@FHell I first tried it exactly like this. If I remember correctly, I ran into problems with integrator.f = fault_f giving strange error messages. Also, after reinit!, the solution object is not extended, but overwritten. The reason seems to me that these counters, which I set manually my implementation, are resetted. 

For me, the nicest solution would be to have an option for initialising the sol  object in the ODEProblem not as an empty array of x0's type but  with "historical data" from a previous simulation.

**Comment by janlisse** [comment]
@FHell I'm not sure if i understand your point. When i use rhs(powergrid) or rhs(pd(powergrid))
the resulting ODEFunction is constructed on-the-fly via NetworkDynamics. So any changes of Jacobian information should be reflected as well.

**Comment by janlisse** [comment]
According to Chris Rackauckas the follwowing code should do:
```
# this doesn't work & hangs in an infinite loop
function simulate(pd::PowerDrop, powergrid, x0, timespan)
    @assert first(timespan) <= pd.tspan_fault[1] "fault cannot begin in the past"
    @assert pd.tspan_fault[2] <= last(timespan) "fault cannot end in the future"

    problem = ODEProblem{true}(deepcopy(rhs(pd(powergrid))), x0.vec, timespan)
    integrator = init(problem, Rodas4(autodiff=false))

    step!(integrator, pd.tspan_fault[1], true)

    # update integrator with error
    integrator.f = rhs(pd(powergrid))
    u_modified!(integrator,true)

    step!(integrator, pd.tspan_fault[2], true)

    # update integrator, clear error
    integrator.f = rhs(powergrid)

    solve!(integrator)

    return PowerGridSolution(integrator.sol, powergrid)
end
```
But with our rhs functions this runs into an infinite loop. The problem seems to have to do with the way  we construct the ODEFunction. There seems to be some shared state between the normal and the error ODEFunction. This is just my guess..

**Comment by FHell** [comment]
> @FHell I'm not sure if i understand your point. When i use rhs(powergrid) or rhs(pd(powergrid))
> the resulting ODEFunction is constructed on-the-fly via NetworkDynamics. So any changes of Jacobian information should be reflected as well.

My point was that your

```
struct Fault
    rhs_normal
    rhs_fault
    ...
end
```

doesn't expose all the information of the underlying "rhs" to the ODEProblem you construct in

```
ODEProblem{true}(fault, x0.vec, timespan, p)
```

and further that a change in the massmatrix is not automatically reflected because the massmatrix is not called with (p).

I like the integrator approach. I think we should try to get that to work. If it's still on the table then I will spend some time on this after my holiday.

**Comment by janlisse** [comment]
Ah, now i got your point! Yes, it would be nice to get the integrator stuff working somehow.

**Comment by luap-pik** [comment]
@dombaier I just add you to this thread. :-)

@all What are the ToDos with the integrator approach in your opinion?

**Comment by janlisse** [comment]
@luap-pik get it running ;) the code is basically there.

**Comment by janlisse** [comment]
Just a short wrap-up from my side. I experimented a bit with the different implementations and used 
a condensed 2 node example for that. It turned out that for this simple setup the integrator rhs function switching code is working, but it is much slower than anything else. I'm not sure why, though.
The best results i got if i didn't use the integrator interface and switched the Equations only via a parameter. Maybe we can build a generic feature aka "Parameter scaling" that allows to scale any node or line parameter. That would at least be enough for PowerDrop & NodeShortCircuit fault simulations. It wouldn't address the issue of changing the massmatrix @FHell mentioned. But i guess that is a different beast. To go on with the PowerDrop feature for now i would recommend to use @luap-pik code because it is functional and performs ok. Midterm we could implement this a bit cleaner if we have the generic parameter scaling in place. What do you think @FHell  & @luap-pik ?

**Comment by janlisse** [comment]
With my simple setup from aboive i was able to reproduce a possible bug in DifferentialEquations.
I raised an issue here: https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/491
When this is fixed my code from here: https://github.com/JuliaEnergy/PowerDynamics.jl/issues/41#issuecomment-523008625 should work fine and we can use that implementation for a general fault design.

**Comment by janlisse** [comment]
Done with https://github.com/JuliaEnergy/PowerDynamics.jl/pull/56
