### ISSUE TITLE
Ad-hoc definition of node types

### ISSUE THREAD

**Issue by luap-pik** [JuliaEnergy/PowerDynamics.jl#71]
Problem:
I want to use a custom node type for an analysis and do this using the @DynamicNode macro.
However, several internal methods are created for the new type and work in my script but are not available to other functions in PowerDynamics (see code example below). 

Workaround:
I need to dev PowerDynamics.jl locally and add the new node type to the source s.t. it's available via `using PowerDynamics`. 

Sidenote:
I also needed manual imports to make the macro run. This might be related.

```julia
import Base: @__doc__ #-> LoadError: UndefVarError: @__doc__ not defined
import PowerDynamics: AbstractNode #-> UndefVarError: AbstractNode not defined
```

Example:

```julia
using PowerDynamics
import Base: @__doc__ #-> LoadError: UndefVarError: @__doc__ not defined
import PowerDynamics: AbstractNode #-> UndefVarError: AbstractNode not defined


@DynamicNode MySwingEq(P, H, D, Ω) begin
PowerDynamics.MassMatrix(;m_u = true, m_int = [1, 0])
end begin
@assert D > 0 "damping (D) should be >0"
@assert H > 0 "inertia (H) should be >0"
Ω_H = Ω * 2pi / H
end [[ω, dω]] begin
p = real(u * conj(i_c))
dϕ = ω # dϕ is only a temp variable that Julia should optimize out
du = u * im * dϕ
dω = (P - D*ω - p)*Ω_H
end

showdefinition(stdout, MySwingEq) |> println

swing_node = MySwingEq(P=1., H=1., D=0.1, Ω=50.)
slack = SlackAlgebraic(U=1.)

nodes = [swing_node, slack]

lines = [StaticLine(from=1, to=2, Y=1. + 5. * im)]

pg = PowerGrid(nodes, lines)

# The methods created by the macro are working here...

dimension(swing_node)
symbolsof(swing_node)

# The following two lines both fail with:
#   MethodError: no method matching dimension(::MySwingEq)
# This leads to subsequent errors e.g. in find_operationpoint or find_valid_initial_condition.

systemsize(pg)
```

**Comment by SabineAuer** [comment]
I don't think, this is a bug in the node macro.
The example code you posted shows the work around only. Eventually you can show me your try to create a new node by creating a new branch (since this would be necessary for a new node type anyways for having a PR at the end) so I can rerun the code myself.

**Comment by FHell** [comment]
So the intention is that users of PowerDynamics can not create their own NodeTypes without changing the Package?

**Comment by janlisse** [comment]
I think it should definitely be possible for users to implement their custom node types outside of PowerDynamics, if it is not we should fix it.

**Comment by luap-pik** [comment]
@SabineAuer : I do not want to create a new node type in PowerDynamics, the idea was to define a custom node type in a user script to test some ideas (this is what the example reproduces).

The example leads to error messages probably related to the node macro. Unfortunately I don't understand it well enough yet to propose a fix for this issue. Apparently, some methods defined by the macro don't end up in the right namespace or sth. like that.

**Comment by timkittel** [comment]
I think this is not a bug, but a feature request (:

Just a guess: A solution might just be to adjust this line https://github.com/JuliaEnergy/PowerDynamics.jl/blob/2cae8d221966062665cc2819255f221dfde434c7/src/nodes/NodeMacro.jl#L62 that the macro produces something like `struct PowerDynamics.MySwingEq <: ...` instead of `struct MySwingEq <: ...`. And in the script, you would need to use `import PowerDynamics` instead of `using PowerDynamics`.

**Comment by timkittel** [comment]
I wrote a `showdefinition` (or similar, unsure with the name) function, that shows the full output of what is created from the macro. That should help to continue from there.

**Comment by SabineAuer** [comment]
@luap-pik: I discussed this with Jan again and we also think, this is a feature request then, not a bug. Can you change the label accordingly?
Also, can you provide your code in a file in a new branch. Even if you do not want to add it as a new node type but as a run example with customized nodes outside of PowerDynamics,  I still think, it is good practice to create a branch so I can reproduce your problem and then I will look what adjustments we can make in PowerDynamics to make your example work such that customized node types can be created.

**Comment by luap-pik** [comment]
I created a new [branch](https://github.com/JuliaEnergy/PowerDynamics.jl/tree/Issue71)

**Comment by janlisse** [comment]
Hey @luap-pik ,
i just had a look at your issue and the main problem is not in PowerDynamics but in your example script.
To fix the error you need to add this line:
https://github.com/JuliaEnergy/PowerDynamics.jl/blob/e7dd641ff63254acc4039a2e2cb5063b6e71fb48/adhoc_node_definition.jl#L3
I fixed it on your branch and then it works just fine.
This is completely expected because you are defining a new node type with new methods for the functions: `dimension`, `symbolsof`,`construct_vertex` and `showdefinition` already defined in the PowerDynamics module. Explicitly importing them tells Julia that you want to modify/add methods from another module namespace.
Nevertheless your example script also showed some minor issues on the PowerDynamics side that are cumbersome if you define new node types in your own module. 
First the awkward need for a `import Base.__doc__` statement and secondly a missing module export of `AbstractNode` in PD. I fixed both issues and simplified your example accordingly.

**Comment by luap-pik** [comment]
Dear @janlisse ,
thank's a lot! I should have thought of this myself since this import is always needed when methods are extended. Shame on me ;-)
